version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Монтируем текущую директорию внутрь контейнера
    depends_on:
      - db
    command: ["uvicorn", "script:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: FrontendDockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  postgres-data: